version: '3.9'
services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./packages/:/var/www/packages
      - ./projects/:/var/www/projects
  nginx:
    image: nginx
    working_dir: "/var/www/"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./projects/backend-api-platform:/var/www/projects/backend-api-platform
      - ./docker/nginx/log/:/var/log/nginx/
      - ./docker/nginx/conf.d/symfony.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
